### ISSUE TITLE
실행 화면 Screenshot 추가

### ISSUE THREAD

**Issue by wisemuji** [app-and-me/App_and_Me_Website#12]
![메인화면](https://user-images.githubusercontent.com/32327475/57664695-3620b180-7634-11e9-86f7-d76ebe95d1e3.png)
![About](https://user-images.githubusercontent.com/32327475/57664707-40db4680-7634-11e9-877e-e25eec997b6d.png)
![부원소개](https://user-images.githubusercontent.com/32327475/57664728-56507080-7634-11e9-85bd-0cc3faf8149b.png)
![지원현황](https://user-images.githubusercontent.com/32327475/57664752-68321380-7634-11e9-98c3-65c1276cb555.png)
![개발일지](https://user-images.githubusercontent.com/32327475/57664781-77b15c80-7634-11e9-86b6-069aba9822f8.png)
![Q&A](https://user-images.githubusercontent.com/32327475/57664798-81d35b00-7634-11e9-8c1f-b4367093feec.png)

**Comment by shinsunyoung** [comment]
안녕하세요 wisemuji님!
이슈 닫아주세요. 이미 추가되어있는 것 같아요!

**Comment by wisemuji** [comment]
안녕하세요 shinsunyoung님~~
이슈 감사합니다~~~~~
